#! /bin/sh

######################################################
##	 ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓  
##	▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒  
##	▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░  
##	▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██   
##	░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒  
##	░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░  
##	▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  
##	 ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     
##	 ░            ░               ░           ░     
##	      ░                                         
######################################################


## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		let name++
	done
}
workspaces

bspc config top_padding 57
bspc config border_width 0
bspc config window_gap 12
bspc config split_ratio 0.50

# bspc config focused_border_color "$BACKGROUND" 
# bspc config normal_border_color "$BACKGROUND"
bspc config presel_feedback_color "$BLACK"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# EWW
eww daemon &

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager

# Lauch notification daemon
dunst --config $HOME/.config/dunst/dunstrc &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# start polybar
~/.config/polybar/launch.sh &

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspcomp
bspfloat &

