#!/usr/bin/env sh

##====================================================
##	 ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓  
##	▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒  
##	▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░  
##	▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██   
##	░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒  
##	░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░  
##	▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  
##	 ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     
##	 ░            ░               ░           ░     
##	      ░                                         
##====================== By: Rxyhn  ==================

## Environments.

export PATH="${PATH}:${HOME}/.config/bspwm/bin"

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

## Parse colors from "~/.Xresources" ---------------------------- #

xrdb -override "${HOME}/.Xresources"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors()
{
    #FOREGROUND="$(xrdb_query '*.foreground:')"
    BACKGROUND="$(xrdb_query '*.background:')"
    BLACK="$(xrdb_query '*.color0:')"
    #RED="$(xrdb_query '*.color1:')"
    #GREEN="$(xrdb_query '*.color2:')"
    #YELLOW="$(xrdb_query '*.color3:')"
    #BLUE="$(xrdb_query '*.color4:')"
    #MAGENTA="$(xrdb_query '*.color5:')"
    #CYAN="$(xrdb_query '*.color6:')"
    #WHITE="$(xrdb_query '*.color7:')"
}

getcolors

## Configurations ----------------------------------------------- #

bspc monitor -d I II III IV V VI VII

rule firefox                        desktop=I
rule discord                        desktop=II
rule Code                           desktop=III

config top_padding 40
config border_width 4
config window_gap 10
config split_ratio 0.50

config focused_border_color "$BLACK"
config normal_border_color "$BLACK"
config presel_feedback_color "$BLACK"

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

## Startup programs --------------------------------------------- #

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Double Border
pkill 2bspwm ; 2bspwm &

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Run notification daemon.
dunst --config "${HOME}/.config/dunst/dunstrc" &

# Run EWW.
$HOME/.local/bin/eww daemon &
sh $HOME/.config/eww/dashboard/scripts/weather_info --getdata &
sh $HOME/.config/eww/sidebar/scripts/getWeather &

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Run power manager.
xfce4-power-manager &

# Run mpd if doesn't started.
[ -n "$(pidof mpd)" ] || mpd &

# Execute bspwm-specific scripts.
bspfloat &

# Start X wallpaper.
feh --no-fehbg --bg-fill "${HOME}/Pictures/Wallpapers/Nord/nordCloud.png" 

# Start polybar
sh $HOME/.config/polybar/launch.sh

# Fix cursor.
xsetroot -cursor_name left_ptr 
