#! /bin/sh

######################################################
##	 ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓  
##	▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒  
##	▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░  
##	▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██   
##	░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒  
##	░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░  
##	▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░  
##	 ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░     
##	 ░            ░               ░           ░     
##	      ░                                         
######################################################


## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		let name++
	done
}
workspaces

bspc config top_padding 60
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BACKGROUND" 
bspc config normal_border_color "$BACKGROUND"
bspc config presel_feedback_color "$BACKGROUND"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# EWW
eww daemon &

# Lauch notification daemon
dunst --config $HOME/.config/dunst/dunstrc &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Wallpapers
feh --no-fehbg --bg-tile '/home/rxyhn/Pictures/Wallpapers/tile_x.png' 

# start polybar
~/.config/polybar/launch.sh 

# Start mpd
exec mpd &

# Start bspwm scripts
bspcomp
bspfloat &

