#!/bin/bash
# Bash Menu Script Installasion Depedency and fish shell

# update first
sudo pacman -Syyu || error "Error syncing the repos."

# make ricing directory
mkdir $HOME/Documents/Rice

# Banner
echo -e ""
echo -e "         
░█████╗░███████╗░██████╗████████╗██╗░░██╗███████╗████████╗██╗░█████╗░
██╔══██╗██╔════╝██╔════╝╚══██╔══╝██║░░██║██╔════╝╚══██╔══╝██║██╔══██╗
███████║█████╗░░╚█████╗░░░░██║░░░███████║█████╗░░░░░██║░░░██║██║░░╚═╝
██╔══██║██╔══╝░░░╚═══██╗░░░██║░░░██╔══██║██╔══╝░░░░░██║░░░██║██║░░██╗
██║░░██║███████╗██████╔╝░░░██║░░░██║░░██║███████╗░░░██║░░░██║╚█████╔╝
╚═╝░░╚═╝╚══════╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░╚════╝░"
echo -e ""
echo -e "      Script For Installasion Depedency And Some Stuff © @ghost"
echo -e ""

# Main
PS3='Please enter your choice: '
options=("Install Depedency [ Pacman ]" "Install [ yay ]" "Install Depedency [ yay ]" "Install [ bspwm ]" "Install Depedency [ zsh ]" "Install [ icon and theme ]" "Exit" )
select opt in "${options[@]}"
do
    case $opt in
        "Install Depedency [ Pacman ]")
            sudo pacman -Sy --needed acpi alsa-plugins alsa-tools alsa-utils bspwm sxhkd bmon dialog dmenu dunst firefox feh fsarchiver gtk-engine-murrine gpick ffmpeg ffmpegthumbnailer gvfs gvfs-afc gvfs-google gvfs-gphoto2 gvfs-mtp gvfs-smb highlight htop imagemagick inetutils inotify-tools kitty libfm libva-mesa-driver light lxappearance maim mesa mpc mpd mpv mtools ncmpcpp network-manager-applet networkmanager nfs-utils openssh pavucontrol pulseaudio pulseaudio-alsa pulseaudio-bluetooth pulseaudio-equalizer-ladspa pulsemixer ranger reflector rofi rsync rxvt-unicode-terminfo thunar thunar-archive-plugin thunar-media-tags-plugin thunar-volman ttf-dejavu ueberzug unrar unzip vulkan-radeon wpa_supplicant wmctrl xarchiver xclip xdg-user-dirs xdg-user-dirs-gtk xdg-utils xf86-video-amdgpu xf86-video-ati xf86-video-vesa xfce4-power-manager xfce4-settings youtube-dl zathura zsh xorg xorg-server jq xsettingsd dosfstools polkit zip tmux neovim playerctl wireless_tools fzf
            echo "----------------------------"
            echo " install depedency finished "
            echo "----------------------------"
            ;;
        "Install [ yay ]")
            cd $HOME/Documents/Rice && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
            echo "----------------------------"
            echo " install yay finished "
            echo "----------------------------"
            ;;
        "Install Depedency [ yay ]")
            yay -S --noconfirm --needed lightdm lightdm-slick-greeter lightdm-settings ttf-fira-code nerd-fonts-fira-code afetch brightnessctl cava eww-git i3lock-color papirus-icon-theme papirus-linux-universe picom-ibhagwan-git polybar visual-studio-code-bin spotify xfce-polkit plymouth plymouth-theme-spinner-alt-git todo-bin
            echo "----------------------------"
            echo " install depedency finished "
            echo "----------------------------"
            ;;
        "Install [ bspwm ]")
            mkdir -p $HOME/.config/{bspwm,sxhkd} && install -Dm755 /usr/share/doc/bspwm/examples/bspwmrc $HOME/.config/bspwm/bspwmrc && install -Dm644 /usr/share/doc/bspwm/examples/sxhkdrc $HOME/.config/sxhkd/sxhkdrc 
            echo "----------------------------"
            echo " install bspwm finished "
            echo "----------------------------"
            ;;
        "Install Depedency [ zsh ]")
            git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
            echo "----------------------------"
            echo " install zsh finished "
            echo "----------------------------"
            ;;
        "Install [ icon and theme ]")
            mkdir $HOME/Documents/Rice/icon-theme && cd $HOME/Documents/Rice/icon-theme && git clone https://github.com/vinceliuice/Qogir-icon-theme.git && git clone https://github.com/EliverLara/Nordic.git && git clone https://github.com/Adapta-Projects/Papirus-Nord.git
            echo "----------------------------"
            echo " install icon and theme finished "
            echo "----------------------------"
            ;;
        "Exit")
            exit 0
            ;;
        *) echo "Invalid Selection $REPLY";;
    esac
  break
done

