#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"


## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi


## Open widgets 
run_eww() {
	eww -c ~/.config/eww/sidebar open-many \
		   bg_side \
		   time_side \
		   date_side \
		   system_side \
		   music_side \
		   weather_side \
		   power_side 

}

close_eww() {
	eww -c ~/.config/eww/sidebar close \
		   bg_side \
		   time_side \
		   date_side \
		   system_side \
		   music_side \
		   weather_side \
		   power_side 
}


## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE" &&
	run_eww

else
	close_eww
	rm "$FILE"
fi
