#!/bin/bash

uri=$(curl -s "https://api.quotable.io/random?maxLength=32")
quote=$(echo $uri | jq '.content' | cut -d "\"" -f 2)
author=$(echo $uri | jq '.author' | cut -d "\"" -f 2)

case $1 in
    quote)
        echo $quote
        ;;
    author)
        echo $author
        ;;
esac
