#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"


## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	eww -c ~/.config/eww/dashboard open-many \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   music \
		   github \
		   reddit \
		   twitter \
		   youtube \
		   weather \
		   apps \
		   mail \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders
}

close_eww() {
	eww -c ~/.config/eww/dashboard close \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   music \
		   github \
		   reddit \
		   twitter \
		   youtube \
		   weather \
		   apps \
		   mail \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders
}


## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	close_eww
	rm "$FILE"
fi
