#!/bin/bash



uri=$(curl -s "https://api.quotable.io/random?maxLength=32")
quote=$(echo $uri | jq '.content' | cut -d "\"" -f 2)
author=$(echo $uri | jq '.author' | cut -d "\"" -f 2)


if [ "$quote" = "" ] ; then
	quote="Bad programmers worry about the code."
    author="Linus Torvalds"
fi

case $1 in
    quote)
        echo $quote
        ;;
    author)
        echo "- $author"
        ;;
esac