#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Simple Script To Pick Color Quickly.

color=$(gpick -pso --no-newline)

main() {
	if [[ "$color" ]]; then
		# copy color code to clipboard
		echo $color | tr -d "\n" | xclip -selection clipboard
		# notify about it
		dunstify -u low --replace=69 -i /usr/share/archcraft/icons/dunst/dropper.png "$color, copied to clipboard."
	fi
}

# Run the script
main
