#!/bin/bash
tmp_dir="$HOME/.cache/eww/spotify"
tmp_cover_path=$tmp_dir/cover.png
tmp_temp_path=$tmp_dir/temp.png

if [ ! -d $tmp_dir ]; then
	mkdir -p $tmp_dir
fi

artlink="$(playerctl -p spotify metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"

if [ $(playerctl -p spotify metadata mpris:artUrl) ]; then
	curl -s "$artlink" --output $tmp_temp_path
else
	cp $HOME/.config/eww/assets/fallback.png $tmp_temp_path
fi

# an epic effekt
convert $tmp_temp_path -alpha set -channel A -evaluate multiply 0.3  $tmp_cover_path
# convert $tmp_temp_path -gravity center +repage -alpha set -channel A \
#     -sparse-color Barycentric '%[fx:w*2/32],0 opaque  %[fx:w+0.5],0 transparent' \
# 	-evaluate multiply 0.3 \
#     $tmp_cover_path
