#!/bin/bash

## Open folders in thunar
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.local/bin/eww"

if [[ "$1" == "--dl" ]]; then
	${EWW} -c $HOME/.config/eww/dashboard close-all && rm -rf "$FILE" && thunar ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	${EWW} -c $HOME/.config/eww/dashboard close-all && rm -rf "$FILE" && thunar ~/Documents &

elif [[ "$1" == "--music" ]]; then
	${EWW} -c $HOME/.config/eww/dashboard close-all && rm -rf "$FILE" && thunar ~/Music &

elif [[ "$1" == "--pics" ]]; then
	${EWW} -c $HOME/.config/eww/dashboard close-all && rm -rf "$FILE" && thunar ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	${EWW} -c $HOME/.config/eww/dashboard close-all && rm -rf "$FILE" && thunar ~/.config &

elif [[ "$1" == "--local" ]]; then
	${EWW} -c $HOME/.config/eww/dashboard close-all && rm -rf "$FILE" && thunar ~/.local/share &

fi
